# Generated by Django 4.0.4 on 2022-05-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.TextField(blank=True, null=True)),
                ('due_created', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['done'],
            },
        ),
    ]
